USE master;

BEGIN TRANSACTION;

CREATE SCHEMA RADIUM;
GO

CREATE TABLE RADIUM.Sucursal (
    SUCURSAL_ID INT IDENTITY(1,1) PRIMARY KEY,
    SUCURSAL_CODIGO INT,
    SUCURSAL_NOMBRE NVARCHAR(255),
    SUCURSAL_DIRECCION NVARCHAR(255),
    SUCURSAL_TELEFONO NVARCHAR(20),
    SUCURSAL_LOCALIDAD_ID INT,
    SUCURSAL_PROVINCIA_ID INT
);
GO

CREATE TABLE RADIUM.Inmueble (
    INMUEBLE_ID INT IDENTITY(1,1) PRIMARY KEY,
    INMUEBLE_CODIGO INT,
    INMUEBLE_NOMBRE NVARCHAR(255),
    INMUEBLE_DESCRIPCION NVARCHAR(MAX),
    INMUEBLE_DIRECCION NVARCHAR(255),
    INMUEBLE_SUPERFICIE_TOTAL DECIMAL(10, 2),
    INMUEBLE_ANTIGUEDAD INT,
    INMUEBLE_EXPENSAS DECIMAL(10, 2),
    INMUEBLE_CARACTERISTICA_WIFI BIT,
    INMUEBLE_CARACTERISTICA_CABLE BIT,
    INMUEBLE_CARACTERISTICA_CALEFACCION BIT,
    INMUEBLE_CARACTERISTICA_GAS BIT,
    INMUEBLE_BARRIO_ID INT,
    INMUEBLE_LOCALIDAD_ID INT,
    INMUEBLE_PROVINCIA_ID INT,
    INMUEBLE_TIPO_INMUEBLE_ID INT,
    INMUEBLE_PROPIETARIO_ID INT,
    INMUEBLE_CANT_AMBIENTES_ID INT,
    INMUEBLE_ORIENTACION_ID INT,
    INMUEBLE_DISPOSICION_ID INT,
    INMUEBLE_ESTADO_ID INT
);
GO

CREATE TABLE RADIUM.Propietario (
    PROPIETARIO_ID INT IDENTITY(1,1) PRIMARY KEY,
    PROPIETARIO_DNI NVARCHAR(20),
    PROPIETARIO_NOMBRE NVARCHAR(255),
    PROPIETARIO_APELLIDO NVARCHAR(255),
    PROPIETARIO_FECHA_REGISTRO DATETIME,
    PROPIETARIO_TELEFONO NVARCHAR(20),
    PROPIETARIO_MAIL NVARCHAR(255),
    PROPIETARIO_FECHA_NAC DATETIME
);
GO

CREATE TABLE RADIUM.Agente (
    AGENTE_ID INT IDENTITY(1,1) PRIMARY KEY,
    AGENTE_DNI NVARCHAR(20),
    AGENTE_NOMBRE NVARCHAR(255),
    AGENTE_APELLIDO NVARCHAR(255),
    AGENTE_FECHA_REGISTRO DATETIME,
    AGENTE_TELEFONO NVARCHAR(20),
    AGENTE_MAIL NVARCHAR(255),
    AGENTE_FECHA_NAC DATETIME
);
GO

CREATE TABLE RADIUM.Tipo_Operacion (
    TIPO_OPERACION_ID INT IDENTITY(1,1) PRIMARY KEY,
    TIPO_OPERACION_NOMBRE NVARCHAR(255)
);
GO

CREATE TABLE RADIUM.Moneda (
    MONEDA_ID INT IDENTITY(1,1) PRIMARY KEY,
    MONEDA_NOMBRE NVARCHAR(255)
    CONSTRAINT UQ_MONEDA_NOMBRE UNIQUE(MONEDA_NOMBRE)
);

CREATE TABLE RADIUM.Alquiler (
    ALQUILER_ID INT IDENTITY(1,1) PRIMARY KEY,
    ALQUILER_CODIGO INT,
    ALQUILER_FECHA_INICIO DATETIME,
    ALQUILER_FECHA_FIN DATETIME,
    ALQUILER_CANT_PERIODOS INT,
    ALQUILER_DEPOSITO DECIMAL(10, 2),
    ALQUILER_COMISION DECIMAL(10, 2),
    ALQUILER_GASTOS_AVERIGUA DECIMAL(10, 2),
    INQUILINO_ID INT,
    ALQUILER_ESTADO NVARCHAR(255),
    ALQUILER_DETALLE_IMPORTE_ID INT
);
GO

CREATE TABLE RADIUM.Venta (
    VENTA_ID INT PRIMARY KEY,
    VENTA_FECHA DATETIME,
    VENTA_PRECIO_VENTA DECIMAL(10, 2),
    VENTA_COMISION DECIMAL(10, 2),
    COMPRADOR_ID INT,
    VENTA_MONEDA_ID INT
);
GO

CREATE TABLE RADIUM.Medio_Pago (
    MEDIO_PAGO_ID INT IDENTITY(1,1) PRIMARY KEY,
    TIPO_MEDIO_PAGO NVARCHAR(30)
)

CREATE TABLE RADIUM.Pago_Alquiler (
    PAGO_ALQUILER_ID INT PRIMARY KEY,
    PAGO_ALQUILER_FECHA DATETIME,
    PAGO_ALQUILER_FECHA_VENCIMIENTO DATETIME,
    PAGO_ALQUILER_NRO_PERIODO INT,
    PAGO_ALQUILER_DESC NVARCHAR(MAX),
    PAGO_ALQUILER_FEC_INI DATETIME,
    PAGO_ALQUILER_FEC_FIN DATETIME,
    PAGO_ALQUILER_IMPORTE DECIMAL(10, 2),
    PAGO_ALQUILER_MEDIO_PAGO_ID INT
);
GO

CREATE TABLE RADIUM.Pago_Venta (
    PAGO_VENTA_ID INT IDENTITY(1,1) PRIMARY KEY,
    PAGO_VENTA_IMPORTE DECIMAL(10, 2),
    PAGO_VENTA_MONEDA INT,
    PAGO_VENTA_COTIZACION DECIMAL(10, 2),
    PAGO_VENTA_MEDIO_PAGO INT
);
GO

CREATE TABLE RADIUM.Detalle_Importe (
    DETALLE_IMPORTE_ID INT IDENTITY(1,1) PRIMARY KEY,
    DETALLE_IMPORTE_PERIODO_INI DATETIME,
    DETALLE_IMPORTE_PERIODO_FIN DATETIME,
    DETALLE_IMPORTE_PRECIO DECIMAL(10, 2)
);
GO

CREATE TABLE RADIUM.Comprador (
    COMPRADOR_ID INT IDENTITY(1,1) PRIMARY KEY,
    COMPRADOR_DNI NVARCHAR(20),
    COMPRADOR_NOMBRE NVARCHAR(255),
    COMPRADOR_APELLIDO NVARCHAR(255),
    COMPRADOR_FECHA_REGISTRO DATETIME,
    COMPRADOR_TELEFONO NVARCHAR(20),
    COMPRADOR_MAIL NVARCHAR(255),
    COMPRADOR_FECHA_NAC DATETIME
);
GO

CREATE TABLE RADIUM.Inquilino (
    INQUILINO_ID INT IDENTITY(1,1) PRIMARY KEY,
    INQUILINO_DNI NVARCHAR(20),
    INQUILINO_NOMBRE NVARCHAR(255),
    INQUILINO_APELLIDO NVARCHAR(255),
    INQUILINO_FECHA_REGISTRO DATETIME,
    INQUILINO_TELEFONO NVARCHAR(20),
    INQUILINO_MAIL NVARCHAR(255),
    INQUILINO_FECHA_NAC DATETIME
);
GO

CREATE TABLE RADIUM.Tipo_Inmueble (
    TIPO_INMUEBLE_ID INT IDENTITY(1,1) PRIMARY KEY,
    TIPO_INMUEBLE_TIPO NVARCHAR(255)
);
GO

CREATE TABLE RADIUM.Provincia (
    PROVINCIA_ID INT IDENTITY(1,1) PRIMARY KEY,
    PROVINCIA_NOMBRE NVARCHAR(255)
);
GO

CREATE TABLE RADIUM.Localidad (
    LOCALIDAD_ID INT IDENTITY(1,1) PRIMARY KEY,
    LOCALIDAD_NOMBRE NVARCHAR(255)
);
GO

CREATE TABLE RADIUM.Barrio (
    BARRIO_ID INT IDENTITY(1,1) PRIMARY KEY,
    BARRIO_NOMBRE NVARCHAR(255)
);
GO

CREATE TABLE RADIUM.Ambientes (
    AMBIENTES_ID INT IDENTITY(1,1) PRIMARY KEY,
    AMBIENTES_CANTIDAD NVARCHAR(40)
);
GO

CREATE TABLE RADIUM.Disposicion (
    DISPOSICION_ID INT IDENTITY(1,1) PRIMARY KEY,
    DISPOSICION_UBICACION NVARCHAR(255)
);
GO

CREATE TABLE RADIUM.Orientacion (
    ORIENTACION_ID INT IDENTITY(1,1) PRIMARY KEY,
    ORIENTACION_CARDINAL NVARCHAR(255)
);
GO

CREATE TABLE RADIUM.Estado_Inmueble (
    ESTADO_ID INT IDENTITY(1,1) PRIMARY KEY,
    ESTADO_TIPO NVARCHAR(255)
);
GO

CREATE TABLE RADIUM.Estado_Anuncio (
    ESTADO_ID INT IDENTITY(1,1) PRIMARY KEY,
    ESTADO_TIPO NVARCHAR(255)
);
GO

CREATE TABLE RADIUM.Tipo_Periodo (
    TIPO_PERIODO_ID INT IDENTITY(1,1) PRIMARY KEY,
    TIPO_PERIODO_TIPO NVARCHAR(255)
);
GO

CREATE TABLE RADIUM.Estado_Alquiler (
    ESTADO_ID INT IDENTITY(1,1) PRIMARY KEY,
    ESTADO_TIPO NVARCHAR(255)
);
GO

ALTER TABLE RADIUM.Inmueble
ADD FOREIGN KEY (INMUEBLE_PROPIETARIO_ID) REFERENCES RADIUM.Propietario(PROPIETARIO_ID);
GO

ALTER TABLE RADIUM.Inmueble
ADD FOREIGN KEY (INMUEBLE_TIPO_INMUEBLE_ID) REFERENCES RADIUM.Tipo_Inmueble(TIPO_INMUEBLE_ID);
GO

ALTER TABLE RADIUM.Inmueble
ADD FOREIGN KEY (INMUEBLE_LOCALIDAD_ID) REFERENCES RADIUM.Localidad(LOCALIDAD_ID);
GO

ALTER TABLE RADIUM.Inmueble
ADD FOREIGN KEY (INMUEBLE_DISPOSICION_ID) REFERENCES RADIUM.Disposicion(DISPOSICION_ID);
GO

ALTER TABLE RADIUM.Inmueble
ADD FOREIGN KEY (INMUEBLE_ORIENTACION_ID) REFERENCES RADIUM.Orientacion(ORIENTACION_ID);
GO

ALTER TABLE RADIUM.Inmueble
ADD FOREIGN KEY (INMUEBLE_ESTADO_ID) REFERENCES RADIUM.Estado_Inmueble(ESTADO_ID);
GO

ALTER TABLE RADIUM.Alquiler
ADD FOREIGN KEY (INQUILINO_ID) REFERENCES RADIUM.Inquilino(INQUILINO_ID);
GO

ALTER TABLE RADIUM.Alquiler
ADD FOREIGN KEY (ALQUILER_DETALLE_IMPORTE_ID) REFERENCES RADIUM.Detalle_Importe(DETALLE_IMPORTE_ID);
GO

ALTER TABLE RADIUM.Venta
ADD FOREIGN KEY (COMPRADOR_ID) REFERENCES RADIUM.Comprador(COMPRADOR_ID);
GO

ALTER TABLE RADIUM.Pago_Alquiler
ADD FOREIGN KEY (PAGO_ALQUILER_MEDIO_PAGO_ID) REFERENCES RADIUM.Medio_Pago(MEDIO_PAGO_ID);

ALTER TABLE RADIUM.Pago_Venta
ADD FOREIGN KEY (PAGO_VENTA_MEDIO_PAGO) REFERENCES RADIUM.Medio_Pago(MEDIO_PAGO_ID);
GO

CREATE PROCEDURE RADIUM.MigrarDatosSucursal AS
BEGIN
    INSERT INTO RADIUM.Sucursal (
        SUCURSAL_CODIGO, SUCURSAL_NOMBRE, SUCURSAL_DIRECCION, SUCURSAL_TELEFONO,
        SUCURSAL_LOCALIDAD_ID, SUCURSAL_PROVINCIA_ID
    )
     SELECT DISTINCT
        SUCURSAL_CODIGO, SUCURSAL_NOMBRE, SUCURSAL_DIRECCION, SUCURSAL_TELEFONO,
        LOCALIDAD_ID, PROVINCIA_ID
    FROM gd_esquema.Maestra m
        JOIN RADIUM.Localidad l
            on l.LOCALIDAD_NOMBRE = m.SUCURSAL_LOCALIDAD
        JOIN RADIUM.Provincia p
            on p.PROVINCIA_NOMBRE = m.SUCURSAL_PROVINCIA
END;
GO

CREATE PROCEDURE RADIUM.MigrarDatosInmueble AS
BEGIN
    INSERT INTO RADIUM.Inmueble (
        INMUEBLE_CODIGO, INMUEBLE_NOMBRE, INMUEBLE_DESCRIPCION, INMUEBLE_DIRECCION,
        INMUEBLE_SUPERFICIE_TOTAL, INMUEBLE_ANTIGUEDAD, INMUEBLE_EXPENSAS,
        INMUEBLE_CARACTERISTICA_WIFI, INMUEBLE_CARACTERISTICA_CABLE,
        INMUEBLE_CARACTERISTICA_CALEFACCION, INMUEBLE_CARACTERISTICA_GAS,
        INMUEBLE_BARRIO_ID, INMUEBLE_LOCALIDAD_ID, INMUEBLE_PROVINCIA_ID,
        INMUEBLE_TIPO_INMUEBLE_ID, INMUEBLE_PROPIETARIO_ID, INMUEBLE_CANT_AMBIENTES_ID,
        INMUEBLE_ORIENTACION_ID, INMUEBLE_DISPOSICION_ID, INMUEBLE_ESTADO_ID
    )
    SELECT
        INMUEBLE_CODIGO, INMUEBLE_NOMBRE, INMUEBLE_DESCRIPCION, INMUEBLE_DIRECCION,
        INMUEBLE_SUPERFICIETOTAL, INMUEBLE_ANTIGUEDAD, INMUEBLE_EXPESAS,
        INMUEBLE_CARACTERISTICA_WIFI, INMUEBLE_CARACTERISTICA_CABLE,
        INMUEBLE_CARACTERISTICA_CALEFACCION, INMUEBLE_CARACTERISTICA_GAS,
        BARRIO_ID, LOCALIDAD_ID, PROVINCIA_ID,
        TIPO_INMUEBLE_ID, PROPIETARIO_ID, AMBIENTES_ID,
        ORIENTACION_ID, DISPOSICION_ID, ESTADO_ID
    FROM gd_esquema.Maestra m
        JOIN RADIUM.Propietario p
            ON p.PROPIETARIO_DNI = m.PROPIETARIO_DNI AND p.PROPIETARIO_FECHA_NAC = m.PROPIETARIO_FECHA_NAC
        JOIN RADIUM.Tipo_Inmueble t
            ON t.TIPO_INMUEBLE_TIPO = m.INMUEBLE_TIPO_INMUEBLE
        JOIN RADIUM.Ambientes amb
            ON amb.AMBIENTES_CANTIDAD = m.INMUEBLE_CANT_AMBIENTES
        JOIN RADIUM.Estado_Inmueble est
            ON est.ESTADO_TIPO = m.INMUEBLE_ESTADO
        JOIN RADIUM.Orientacion o
            ON o.ORIENTACION_CARDINAL = m.INMUEBLE_ORIENTACION
        JOIN RADIUM.Disposicion d
            ON d.DISPOSICION_UBICACION = m.INMUEBLE_DISPOSICION
        JOIN RADIUM.Provincia prov
            ON prov.PROVINCIA_NOMBRE = m.INMUEBLE_PROVINCIA
        JOIN RADIUM.Localidad l
            ON l.LOCALIDAD_NOMBRE = m.INMUEBLE_LOCALIDAD
        JOIN RADIUM.Barrio b
            ON b.BARRIO_NOMBRE = m.INMUEBLE_BARRIO
END;
GO

CREATE PROCEDURE RADIUM.MigrarDatosPropietario AS
BEGIN
    INSERT INTO RADIUM.Propietario (
        PROPIETARIO_DNI, PROPIETARIO_NOMBRE, PROPIETARIO_APELLIDO,
        PROPIETARIO_FECHA_REGISTRO, PROPIETARIO_TELEFONO,
        PROPIETARIO_MAIL, PROPIETARIO_FECHA_NAC
    )
    SELECT DISTINCT
        PROPIETARIO_DNI, PROPIETARIO_NOMBRE, PROPIETARIO_APELLIDO,
        PROPIETARIO_FECHA_REGISTRO, PROPIETARIO_TELEFONO,
        PROPIETARIO_MAIL, PROPIETARIO_FECHA_NAC
    FROM gd_esquema.Maestra;
END;
GO

CREATE PROCEDURE RADIUM.MigrarDatosAlquiler AS
BEGIN
    INSERT INTO RADIUM.Alquiler (
        ALQUILER_CODIGO, ALQUILER_FECHA_INICIO, ALQUILER_FECHA_FIN,
        ALQUILER_CANT_PERIODOS, ALQUILER_DEPOSITO, ALQUILER_COMISION,
        ALQUILER_GASTOS_AVERIGUA, INQUILINO_ID, ALQUILER_ESTADO
    )
    SELECT DISTINCT
        ALQUILER_CODIGO, ALQUILER_FECHA_INICIO, ALQUILER_FECHA_FIN,
        ALQUILER_CANT_PERIODOS, ALQUILER_DEPOSITO, ALQUILER_COMISION,
        ALQUILER_GASTOS_AVERIGUA, INQUILINO_ID, ALQUILER_ESTADO
    FROM gd_esquema.Maestra m
        JOIN RADIUM.Inquilino i
            ON i.INQUILINO_DNI = m.INQUILINO_DNI AND i.INQUILINO_FECHA_NAC = m.INQUILINO_FECHA_NAC
        JOIN RADIUM.Detalle_Importe d
            ON d.DETALLE_IMPORTE_PERIODO_INI = m.DETALLE_ALQ_NRO_PERIODO_INI
                AND d.DETALLE_IMPORTE_PERIODO_FIN = m.DETALLE_ALQ_NRO_PERIODO_FIN
                AND d.DETALLE_IMPORTE_PRECIO = m.PAGO_ALQUILER_IMPORTE
END;
GO

CREATE PROCEDURE RADIUM.MigrarDatosVenta AS
BEGIN
    INSERT INTO RADIUM.Venta (
        VENTA_ID, VENTA_FECHA, VENTA_PRECIO_VENTA, VENTA_COMISION,
        COMPRADOR_ID, VENTA_MONEDA_ID
    )
    SELECT DISTINCT
        VENTA_CODIGO, VENTA_FECHA, VENTA_PRECIO_VENTA, VENTA_COMISION,
        COMPRADOR_ID, MONEDA_ID
    FROM gd_esquema.Maestra m
        JOIN RADIUM.Moneda mon
            ON mon.MONEDA_NOMBRE = m.VENTA_MONEDA
        JOIN RADIUM.Comprador com
            ON com.COMPRADOR_DNI = m.COMPRADOR_DNI AND com.COMPRADOR_FECHA_NAC = m.COMPRADOR_FECHA_NAC
END;
GO

CREATE PROCEDURE RADIUM.MigrarDatosPagoAlquiler AS
BEGIN
    INSERT INTO RADIUM.Pago_Alquiler (
        PAGO_ALQUILER_ID, PAGO_ALQUILER_FECHA, PAGO_ALQUILER_FECHA_VENCIMIENTO,
        PAGO_ALQUILER_NRO_PERIODO, PAGO_ALQUILER_DESC, PAGO_ALQUILER_FEC_INI,
        PAGO_ALQUILER_FEC_FIN, PAGO_ALQUILER_IMPORTE, PAGO_ALQUILER_MEDIO_PAGO_ID
    )
    SELECT
        PAGO_ALQUILER_CODIGO, PAGO_ALQUILER_FECHA, PAGO_ALQUILER_FECHA_VENCIMIENTO,
        PAGO_ALQUILER_NRO_PERIODO, PAGO_ALQUILER_DESC, PAGO_ALQUILER_FEC_INI,
        PAGO_ALQUILER_FEC_FIN, PAGO_ALQUILER_IMPORTE, MEDIO_PAGO_ID
    FROM gd_esquema.Maestra m
        JOIN RADIUM.Medio_Pago med
            ON med.TIPO_MEDIO_PAGO = m.PAGO_ALQUILER_MEDIO_PAGO
END;
GO

CREATE PROCEDURE RADIUM.MigrarDatosPagoVenta AS
BEGIN
    INSERT INTO RADIUM.Pago_Venta (
        PAGO_VENTA_IMPORTE, PAGO_VENTA_MONEDA,
        PAGO_VENTA_COTIZACION, PAGO_VENTA_MEDIO_PAGO
    )
    SELECT
        PAGO_VENTA_IMPORTE, MONEDA_ID,
        PAGO_VENTA_COTIZACION, MEDIO_PAGO_ID
    FROM gd_esquema.Maestra m
        JOIN RADIUM.Moneda mon
            ON mon.MONEDA_NOMBRE = m.VENTA_MONEDA
        JOIN RADIUM.Medio_Pago med
            ON med.TIPO_MEDIO_PAGO = m.PAGO_VENTA_MEDIO_PAGO
END;
GO

CREATE PROCEDURE RADIUM.MigrarDatosComprador AS
BEGIN
    INSERT INTO RADIUM.Comprador (
        COMPRADOR_DNI, COMPRADOR_NOMBRE, COMPRADOR_APELLIDO,
        COMPRADOR_FECHA_REGISTRO, COMPRADOR_TELEFONO,
        COMPRADOR_MAIL, COMPRADOR_FECHA_NAC
    )
    SELECT DISTINCT
        COMPRADOR_DNI, COMPRADOR_NOMBRE, COMPRADOR_APELLIDO,
        COMPRADOR_FECHA_REGISTRO, COMPRADOR_TELEFONO,
        COMPRADOR_MAIL, COMPRADOR_FECHA_NAC
    FROM gd_esquema.Maestra WHERE COMPRADOR_DNI is not null;
END;
GO

CREATE PROCEDURE RADIUM.MigrarDatosInquilino AS
BEGIN
    INSERT INTO RADIUM.Inquilino (
        INQUILINO_DNI, INQUILINO_NOMBRE, INQUILINO_APELLIDO,
        INQUILINO_FECHA_REGISTRO, INQUILINO_TELEFONO,
        INQUILINO_MAIL, INQUILINO_FECHA_NAC
    )
    SELECT DISTINCT
        INQUILINO_DNI, INQUILINO_NOMBRE, INQUILINO_APELLIDO,
        INQUILINO_FECHA_REGISTRO, INQUILINO_TELEFONO,
        INQUILINO_MAIL, INQUILINO_FECHA_NAC
    FROM gd_esquema.Maestra WHERE INQUILINO_DNI is not null;
END;
GO

CREATE PROCEDURE RADIUM.MigrarDatosTipoOperacion AS
BEGIN
    INSERT INTO RADIUM.Tipo_Operacion (
        TIPO_OPERACION_NOMBRE
    )
    SELECT
        DISTINCT ANUNCIO_TIPO_OPERACION
    FROM gd_esquema.Maestra;
END;
GO

CREATE PROCEDURE RADIUM.MigrarDatosMoneda AS
BEGIN
    INSERT INTO RADIUM.Moneda (
        MONEDA_NOMBRE
    )
    SELECT DISTINCT MONEDA FROM (
        SELECT DISTINCT VENTA_MONEDA as MONEDA FROM gd_esquema.Maestra
            UNION ALL
        SELECT DISTINCT ANUNCIO_MONEDA FROM gd_esquema.Maestra
            UNION ALL
        SELECT DISTINCT PAGO_VENTA_MONEDA FROM gd_esquema.Maestra
    ) as MVMMAM;
END;
GO

CREATE PROCEDURE RADIUM.MigrarDatosEstadoInmueble AS
BEGIN
    INSERT INTO RADIUM.Estado_Inmueble (
        ESTADO_TIPO
    )
    SELECT DISTINCT
        INMUEBLE_ESTADO
    FROM gd_esquema.Maestra
        WHERE INMUEBLE_ESTADO is not null;
END;
GO

CREATE PROCEDURE RADIUM.MigrarDatosEstadoAnuncio AS
BEGIN
    INSERT INTO RADIUM.Estado_Anuncio (
        ESTADO_TIPO
    )
    SELECT DISTINCT ANUNCIO_ESTADO FROM gd_esquema.Maestra WHERE ANUNCIO_ESTADO is not null;
END;
GO

CREATE PROCEDURE RADIUM.MigrarDatosTipoPeriodo AS
BEGIN
    INSERT INTO RADIUM.Tipo_Periodo (
        TIPO_PERIODO_TIPO
    )
    SELECT DISTINCT
        ANUNCIO_TIPO_PERIODO
    FROM gd_esquema.Maestra;
END;
GO

CREATE PROCEDURE RADIUM.MigrarDatosEstadoAlquiler AS
BEGIN
    INSERT INTO RADIUM.Estado_Alquiler (
        ESTADO_TIPO
    )
    SELECT DISTINCT
        ALQUILER_ESTADO
    FROM gd_esquema.Maestra;
END;
GO

CREATE PROCEDURE RADIUM.MigrarDatosDisposicion AS
BEGIN
    INSERT INTO RADIUM.Disposicion (
        DISPOSICION_UBICACION
    )
    SELECT DISTINCT
        INMUEBLE_DISPOSICION
    FROM gd_esquema.Maestra;
END;
GO

CREATE PROCEDURE RADIUM.MigrarDatosAgente AS
BEGIN
    INSERT INTO RADIUM.Agente (
        AGENTE_DNI,
        AGENTE_NOMBRE,
        AGENTE_APELLIDO ,
        AGENTE_FECHA_REGISTRO,
        AGENTE_TELEFONO,
        AGENTE_MAIL,
        AGENTE_FECHA_NAC
    )
    SELECT DISTINCT
        AGENTE_DNI,
        AGENTE_NOMBRE,
        AGENTE_APELLIDO ,
        AGENTE_FECHA_REGISTRO,
        AGENTE_TELEFONO,
        AGENTE_MAIL,
        AGENTE_FECHA_NAC
    FROM gd_esquema.Maestra;
END;
GO

CREATE PROCEDURE RADIUM.MigrarDatosAmbientes AS
BEGIN
    INSERT INTO RADIUM.Ambientes (
        AMBIENTES_CANTIDAD
    )
    SELECT DISTINCT
        INMUEBLE_CANT_AMBIENTES
    FROM gd_esquema.Maestra;
END;
GO

CREATE PROCEDURE RADIUM.MigrarDatosProvincia AS
BEGIN
    INSERT INTO RADIUM.Provincia (
        PROVINCIA_NOMBRE
    )
    SELECT DISTINCT PROVINCIA FROM
        (SELECT DISTINCT INMUEBLE_PROVINCIA as PROVINCIA FROM gd_esquema.Maestra
        UNION ALL
        SELECT DISTINCT SUCURSAL_PROVINCIA FROM gd_esquema.Maestra)
    as P;
END;
GO

CREATE PROCEDURE RADIUM.MigrarDatosLocalidad AS
BEGIN
    INSERT INTO RADIUM.Localidad (
        LOCALIDAD_NOMBRE
    )
    SELECT DISTINCT LOCALIDAD FROM
        (SELECT DISTINCT INMUEBLE_LOCALIDAD as LOCALIDAD FROM gd_esquema.Maestra
        UNION ALL
        SELECT DISTINCT SUCURSAL_LOCALIDAD FROM gd_esquema.Maestra)
    as L;
END;
GO

CREATE PROCEDURE RADIUM.MigrarDatosBarrio AS
BEGIN
    INSERT INTO RADIUM.Barrio (
        BARRIO_NOMBRE
    )
    SELECT DISTINCT
        INMUEBLE_BARRIO
    FROM gd_esquema.Maestra
END;
GO

CREATE PROCEDURE RADIUM.MigrarRelacionLocalidadProvincia AS
BEGIN
    INSERT INTO RADIUM.Barrio (
        BARRIO_NOMBRE
    )
    SELECT DISTINCT
        INMUEBLE_BARRIO
    FROM gd_esquema.Maestra
END;
GO

CREATE PROCEDURE RADIUM.MigrarDetalleImporteAlquiler AS
BEGIN
    INSERT INTO RADIUM.Detalle_Importe (
        DETALLE_IMPORTE_PERIODO_INI,
        DETALLE_IMPORTE_PERIODO_FIN,
        DETALLE_IMPORTE_PRECIO
    )
SELECT DISTINCT
    DETALLE_ALQ_NRO_PERIODO_INI,
    DETALLE_ALQ_NRO_PERIODO_FIN,
    DETALLE_ALQ_PRECIO
FROM gd_esquema.Maestra m
END;
GO

CREATE PROCEDURE RADIUM.MigrarMediosPago AS
BEGIN
    INSERT INTO RADIUM.Medio_Pago (
        TIPO_MEDIO_PAGO
    )
    SELECT DISTINCT MEDIO_PAGO FROM
        (SELECT DISTINCT PAGO_VENTA_MEDIO_PAGO as MEDIO_PAGO FROM gd_esquema.Maestra
        UNION ALL
        SELECT DISTINCT PAGO_ALQUILER_MEDIO_PAGO as MEDIO_PAGO FROM gd_esquema.Maestra)
    as M;
END;
GO

CREATE PROCEDURE RADIUM.MigrarOrientacion AS
BEGIN
    INSERT INTO RADIUM.Orientacion (
        ORIENTACION_CARDINAL
    )
    SELECT DISTINCT INMUEBLE_ORIENTACION FROM gd_esquema.Maestra;
END;
GO

CREATE PROCEDURE RADIUM.MigrarTipoInmueble AS
BEGIN
    INSERT INTO RADIUM.Tipo_Inmueble (
        TIPO_INMUEBLE_TIPO
    )
    SELECT DISTINCT INMUEBLE_TIPO_INMUEBLE FROM gd_esquema.Maestra;
END;
GO

EXEC RADIUM.MigrarDetalleImporteAlquiler;
GO

EXEC RADIUM.MigrarTipoInmueble;
GO

EXEC RADIUM.MigrarOrientacion;
GO

EXEC RADIUM.MigrarMediosPago;
GO

EXEC RADIUM.MigrarDatosProvincia;
GO

EXEC RADIUM.MigrarDatosLocalidad;
GO

EXEC RADIUM.MigrarDatosBarrio;
GO

EXEC RADIUM.MigrarDatosAmbientes;
GO

EXEC RADIUM.MigrarDatosDisposicion;
GO

EXEC RADIUM.MigrarDatosAgente;
GO

EXEC RADIUM.MigrarDatosMoneda;
GO

EXEC RADIUM.MigrarDatosComprador;
GO

EXEC RADIUM.MigrarDatosInquilino;
GO

EXEC RADIUM.MigrarDatosTipoOperacion;
GO

EXEC RADIUM.MigrarDatosEstadoInmueble;
GO

EXEC RADIUM.MigrarDatosEstadoAnuncio;
GO

EXEC RADIUM.MigrarDatosTipoPeriodo;
GO

EXEC RADIUM.MigrarDatosEstadoAlquiler;
GO

EXEC RADIUM.MigrarDatosSucursal;
GO

EXEC RADIUM.MigrarDatosVenta;
GO

EXEC RADIUM.MigrarDatosPagoAlquiler;
GO

EXEC RADIUM.MigrarDatosPagoVenta;
GO

EXEC RADIUM.MigrarDatosPropietario;
GO

EXEC RADIUM.MigrarDatosAlquiler;
GO

EXEC RADIUM.MigrarDatosInmueble;
GO

COMMIT;